apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4438-go-helloworld-2:fb8ef9c64cc456e877fd8801fe4d3d7350a3667e
        name: go-helloworld-2